--- #YAML:1.0
name:               Constant-Generate
version:            0.04
abstract:           Common tasks for symbolic constants
author:
    - M. Nunberg <mnunberg@haskalah.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:    1.17
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
